# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

development:
  <<: *default
  database: geomatch_development

test:
  <<: *default
  database: geomatch_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    adapter: postgresql
    encoding: unicode
    pool: 5
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    adapter: postgresql
    encoding: unicode
    pool: 5
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    adapter: postgresql
    encoding: unicode
    pool: 5
    url: <%= ENV["DATABASE_URL"] %>