# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

development:
  <<: *default
  database: geomatch_development

test:
  <<: *default
  database: geomatch_test

production:
  <<: *default
  # Render define automaticamente a variável DATABASE_URL,
  # então o Rails se conecta por ela.
  url: <%= ENV["DATABASE_URL"] %>

  # Faz o Solid Queue (fila de jobs) usar o mesmo banco da aplicação.
  connects_to:
    database:
      writing: primary
      queue: primary

# ⚡ Action Cable (Solid Cable)
# Em produção, ele precisa do mesmo banco da aplicação.
cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
