# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["DATABASE_PORT"] || 5432 %>

development:
  <<: *default
  database: geomatch_development

test:
  <<: *default
  database: geomatch_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

  queue:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %> # usa a mesma conexão da aplicação
    migrations_paths: db/queue_migrate

  cable:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %> # o Action Cable (Solid Cable) usa o mesmo banco
