test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

r2:
  service: S3
  access_key_id: <%= ENV["R2_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["R2_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["R2_BUCKET"] %>
  endpoint: <%= ENV["R2_ENDPOINT"] %>
  force_path_style: true
  region: auto

  # ⚠️ NECESSÁRIO PARA R2 FUNCIONAR
  upload:
    checksum: false

  # ⚠️ Rails 7/8 precisam disso também!
  disable_content_md5_validation: true
